/**
 * SAMPLE DATA — used while database is disconnected.
 * All mutations (create/update/delete) operate on these in-memory arrays.
 * Data resets on every page refresh.
 */

import type { ClientWithEvents, Venue } from "@shared/schema";

// ─── Venues ───────────────────────────────────────────────────────────────────
export const sampleVenues: Venue[] = [
  { id: 1, name: "Grand Palace Banquet", location: "Connaught Place, Delhi", capacity: 800, contactPerson: "Rajesh Verma", contactPhone: "+91 98100 11234" },
  { id: 2, name: "The Leela Lawn", location: "Vasant Kunj, Delhi", capacity: 500, contactPerson: "Priya Sharma", contactPhone: "+91 98200 55678" },
  { id: 3, name: "Poolside Gardens", location: "Gurugram, Haryana", capacity: 300, contactPerson: "Amit Kapoor", contactPhone: "+91 99100 77890" },
  { id: 4, name: "Royal Heritage Hall", location: "Jaipur, Rajasthan", capacity: 1200, contactPerson: "Sunita Agarwal", contactPhone: "+91 94130 22345" },
  { id: 5, name: "Riverside Retreat", location: "Rishikesh, Uttarakhand", capacity: 200, contactPerson: "Ravi Nair", contactPhone: "+91 97400 99012" },
];

// ─── Clients with Events ───────────────────────────────────────────────────────
export const sampleClients: ClientWithEvents[] = [
  {
    id: 1,
    clientName: "Sharma Family",
    brideName: "Ananya Sharma",
    groomName: "Vikram Malhotra",
    contactPhone: "+91 98110 12345",
    contactEmail: "sharma.family@email.com",
    alternatePhone: "+91 88010 56789",
    address: "D-42, Lajpat Nagar, New Delhi",
    overallStatus: "confirmed",
    notes: "Client prefers evening ceremonies. Vegetarian catering only.",
    events: [
      {
        id: 101,
        clientId: 1,
        eventType: "mehendi",
        eventDate: "2026-04-18",
        venueName: "Poolside Gardens",
        guestCount: 120,
        startTime: "16:00",
        endTime: "22:00",
        status: "confirmed",
        notes: "Ladies-only gathering for first two hours",
        color: "#2d6e35",
        category: "wedding",
      },
      {
        id: 102,
        clientId: 1,
        eventType: "sangeet",
        eventDate: "2026-04-19",
        venueName: "Grand Palace Banquet",
        guestCount: 350,
        startTime: "19:00",
        endTime: "23:59",
        status: "confirmed",
        notes: "Live band + DJ",
        color: null,
        category: "wedding",
      },
      {
        id: 103,
        clientId: 1,
        eventType: "wedding",
        eventDate: "2026-04-20",
        venueName: '["Grand Palace Banquet","The Leela Lawn"]',
        guestCount: 600,
        startTime: "10:00",
        endTime: "15:00",
        status: "confirmed",
        notes: "Pheras at 11:30 AM. Lunch to follow.",
        color: null,
        category: "wedding",
      },
      {
        id: 104,
        clientId: 1,
        eventType: "reception",
        eventDate: "2026-04-21",
        venueName: "Grand Palace Banquet",
        guestCount: 700,
        startTime: "18:00",
        endTime: "23:00",
        status: "confirmed",
        notes: null,
        color: null,
        category: "wedding",
      },
    ],
  },
  {
    id: 2,
    clientName: "Gupta–Mehta Wedding",
    brideName: "Riya Gupta",
    groomName: "Arjun Mehta",
    contactPhone: "+91 97301 67890",
    contactEmail: "riya.gupta@email.com",
    alternatePhone: null,
    address: "B-12, Rohini Sector 9, Delhi",
    overallStatus: "tentative",
    notes: "Budget-conscious. Exploring outdoor venues.",
    events: [
      {
        id: 201,
        clientId: 2,
        eventType: "engagement",
        eventDate: "2026-05-02",
        venueName: "The Leela Lawn",
        guestCount: 80,
        startTime: "11:00",
        endTime: "14:00",
        status: "tentative",
        notes: "Brunch-style engagement",
        color: "#6b3a7d",
        category: "wedding",
      },
      {
        id: 202,
        clientId: 2,
        eventType: "wedding",
        eventDate: "2026-05-10",
        venueName: "Royal Heritage Hall",
        guestCount: 400,
        startTime: "09:00",
        endTime: "14:00",
        status: "tentative",
        notes: "Tentative — venue confirmation pending",
        color: null,
        category: "wedding",
      },
    ],
  },
  {
    id: 3,
    clientName: "Kapoor Celebrations",
    brideName: "Simran Kapoor",
    groomName: "Nikhil Bhatia",
    contactPhone: "+91 93202 34567",
    contactEmail: "kapoor.celebrations@email.com",
    alternatePhone: "+91 99910 11223",
    address: "C-101, Greater Kailash, New Delhi",
    overallStatus: "confirmed",
    notes: "Destination wedding elements. Floral decor is a priority.",
    events: [
      {
        id: 301,
        clientId: 3,
        eventType: "mehendi",
        eventDate: "2026-06-12",
        venueName: "Riverside Retreat",
        guestCount: 150,
        startTime: "15:00",
        endTime: "21:00",
        status: "confirmed",
        notes: null,
        color: "#2d6e35",
        category: "wedding",
      },
      {
        id: 302,
        clientId: 3,
        eventType: "sangeet",
        eventDate: "2026-06-13",
        venueName: "Riverside Retreat",
        guestCount: 250,
        startTime: "18:00",
        endTime: "23:00",
        status: "confirmed",
        notes: "Bollywood night theme",
        color: "#b85a10",
        category: "wedding",
      },
      {
        id: 303,
        clientId: 3,
        eventType: "wedding",
        eventDate: "2026-06-14",
        venueName: '["Riverside Retreat","Poolside Gardens"]',
        guestCount: 500,
        startTime: "08:00",
        endTime: "13:00",
        status: "confirmed",
        notes: "Sunrise ceremony followed by brunch",
        color: "#0F2A44",
        category: "wedding",
      },
      {
        id: 304,
        clientId: 3,
        eventType: "reception",
        eventDate: "2026-06-15",
        venueName: "Royal Heritage Hall",
        guestCount: 900,
        startTime: "19:00",
        endTime: "23:30",
        status: "confirmed",
        notes: null,
        color: null,
        category: "wedding",
      },
    ],
  },
  {
    id: 4,
    clientName: "Verma Corporate Event",
    brideName: null,
    groomName: null,
    contactPhone: "+91 91100 88776",
    contactEmail: "events@vermagroup.com",
    alternatePhone: null,
    address: "Verma Group HQ, Aerocity, Delhi",
    overallStatus: "confirmed",
    notes: "Annual awards gala. Formal dress code.",
    events: [
      {
        id: 401,
        clientId: 4,
        eventType: "reception",
        eventDate: "2026-04-25",
        venueName: "Grand Palace Banquet",
        guestCount: 200,
        startTime: "19:00",
        endTime: "22:30",
        status: "confirmed",
        notes: "Corporate awards night",
        color: "#1e4d8c",
        category: "corporate",
      },
    ],
  },
  {
    id: 5,
    clientName: "Iyer–Pillai Wedding",
    brideName: "Kavya Iyer",
    groomName: "Siddharth Pillai",
    contactPhone: "+91 84501 23456",
    contactEmail: "kavya.iyer@email.com",
    alternatePhone: null,
    address: "12, Anna Nagar, Chennai",
    overallStatus: "tentative",
    notes: "South Indian ceremony. Specific muhurat dates required.",
    events: [
      {
        id: 501,
        clientId: 5,
        eventType: "engagement",
        eventDate: "2026-05-15",
        venueName: "The Leela Lawn",
        guestCount: 60,
        startTime: "10:00",
        endTime: "13:00",
        status: "tentative",
        notes: null,
        color: "#6b3a7d",
        category: "wedding",
      },
      {
        id: 502,
        clientId: 5,
        eventType: "wedding",
        eventDate: "2026-06-01",
        venueName: "The Leela Lawn",
        guestCount: 300,
        startTime: "06:30",
        endTime: "10:00",
        status: "tentative",
        notes: "Early morning Muhurat — 6:30 AM start is essential",
        color: null,
        category: "wedding",
      },
    ],
  },
];

// ─── ID counters for new records ───────────────────────────────────────────────
let _nextClientId = 10;
let _nextEventId = 1000;
let _nextVenueId = 10;

export function getNextClientId() { return _nextClientId++; }
export function getNextEventId()  { return _nextEventId++; }
export function getNextVenueId()  { return _nextVenueId++; }
